apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-bot-trigger-access
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      - clustertriggerbindings
      - triggerbindings
      - triggertemplates
      - eventlisteners
      - clusterinterceptors
      - interceptors
      - triggers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: build-bot-trigger-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: build-bot-trigger-access
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: tekton-pipelines